### PR TITLE
Update Moving notice

### PR DESCRIPTION
**Pull request by lightfrenzy**

### CODE REVIEW

**Comment by Abhijeet-Xamarin** [comment]
@lightfrenzy May I know new location for this project ? 

I was wondering for changes in "Microsoft Cognitive Services Face API... 1.2.5.1" from "Microsoft Cognitive Services Face API... 1.2.1.2"

please guide me for same?

**Comment by momohs** [comment]
@Abhijeet-Xamarin you can find the different Microsoft Cognitive Face API SDKs [here](https://github.com/Microsoft?utf8=%E2%9C%93&q=cognitive-Face&type=&language=)

**Comment by Abhijeet-Xamarin** [comment]
Thanks @momohs,  hope it is PCL base & targeting to new end points. 

currently project oxford face api is pointing to "westus.api.cognitive.microsoft.com"

I started searching for it because of below mail from Azure. 
"You may be impacted by important changes to Microsoft Cognitive Services, including the retirement of the api.projectoxford.ai endpoint and a new administrative control for enabling Cognitive Services."

**Comment by Abhijeet-Xamarin** [comment]
I just checked that API also uses below nuget 

https://www.nuget.org/packages/Microsoft.ProjectOxford.Face/ 

That is what I am trying to find out, which endpoint it exactly targets? - Please guide me for same.

**Comment by momohs** [comment]
Please send your questions on: https://github.com/Microsoft/Cognitive-Face-Windows

**Pull request merged**
