### PR TITLE
Update OxfordAuthentication.java

### PR DESCRIPTION
**Pull request by tottokug**
Compile Error :LINE 152-155 ,  "Util not found"
I add static class Util , and add getJsonValue

### CODE REVIEW

**Comment by tottokug** [comment]
Is issue necessary?

**Comment by lightfrenzy** [comment]
Hi @tottokug, apologies for the long delay in our response.

We've been working on a big change to our SDK & Sample process in order to better address pull requests and issues from awesome community members like you. From today onward, each project lives in its own repo, specific to its API and platform. 

If you're still interested in contributing (and we hope you are!), please re-file your pull request on the new repo: [https://github.com/Microsoft/cognitive-speech-tts](https://github.com/Microsoft/cognitive-speech-tts).

Thanks again and let me know if you have any questions,
-Allison

**Comment by tottokug** [comment]
Hi @lightfrenzy !
New pull request! => https://github.com/Microsoft/Cognitive-Speech-TTS/pull/3

**Comment by lightfrenzy** [comment]
Sweet -- Thanks!

**Pull request closed without merging**
