### PR TITLE
Added Python libs for majority of voice Verification API calls

### PR DESCRIPTION
**Pull request by khyew**
TODO: add missing call for `List All Supported Verification Phrases`

### CODE REVIEW

**Comment by yungshinlintw** [comment]
Thanks for your contribution! I will contact the speaker identification owner to look into your contributions.

**Comment by momohs** [comment]
@khyew Thanks for your contribution! I did review your contributions and found a couple of comments:

- In the file **PrintAllProfiles.py**, _"Enrollment Speech Time"_ should be changed to _"Enrollments Count"_ and _"Remaining Enrollment Speech Time"_ should be changed to _"Remaining Enrollments Count"_.

- In the file **VerificationServiceHttpClientHelper.py**, there is no need to call the _"_poll_operation"_ function from the _"enroll_profile"_ and _"verify_file"_ functions. In fact, it should be removed along with the member variables that it uses. This is only necessary in the identification service but not the verification service.

**Comment by yungshinlintw** [comment]
@khyew, may I ask your help to sign a contribution form to state that the community is free to benefit from your contribution? https://cla.microsoft.com/ 

Thanks!

**Comment by khyew** [comment]
@momohs Does the Verification Service still return an HTTP 202 at any point, or can that entire branch of the conditional block be eliminated?

**Comment by momohs** [comment]
@khyew the Verification service should not return an HTTP 202 at any point. It is safe to remove the entire branch.

**Comment by khyew** [comment]
I've removed the dead code and updated the wording in the text output.

**Comment by momohs** [comment]
@khyew Thanks for your contribution. I will merge this request now.

**Pull request merged**
